import { InfoLdg } from "types";

export const infos: InfoLdg[] = [
  {
    title: "What we provide",
    description:
      "Create crisp videos that will hook your viewers. It’s never been easier to be create content.",
    image: "/images/work-from-home.jpg",
    list: [
      {
        title: "Diverse",
        description: "Millions of videos. Infinite amount of content.",
        icon: "media",
      },
      {
        title: "Innovative",
        description: "Save time and money on video creation.",
        icon: "check",
      },
      {
        title: "Scalable",
        description:
          "Customise every aspect of the video, or let it run on autopilot. The choice is yours.",
        icon: "search",
      },
    ],
  },
  {
    title: "Seamless Integration",
    description:
      "Integrate our open-source SaaS seamlessly into your existing workflows. Effortlessly connect with your favorite tools and services for a streamlined experience.",
    image: "/images/work-from-home.jpg",
    list: [
      {
        title: "Flexible",
        description:
          "Customize your integrations to fit your unique requirements.",
        icon: "laptop",
      },
      {
        title: "Efficient",
        description: "Streamline your processes and reducing manual effort.",
        icon: "search",
      },
      {
        title: "Reliable",
        description:
          "Rely on our robust infrastructure and comprehensive documentation.",
        icon: "settings",
      },
    ],
  },
];

export const features = [
  {
    title: "Feature 1",
    description:
      "Seamless integration across Twitter, Instagram, Tiktok and many more!",
    link: "/",
  },
  {
    title: "Feature 2",
    description:
      "AI Generated videos generated by your own words",
    link: "/",
  },
  {
    title: "Feature 3",
    description:
      "Schedule the videos and we will take care of the rest.",
    link: "/",
  },
  {
    title: "Feature 4",
    description:
      "Add your teammates for a fully sync collaboration",
    link: "/",
  },
  {
    title: "Feature 5",
    description:
      "Create different length of videos or images, you are in control",
  },
  // {
  //   title: "Feature 6",
  //   description:
  //     "Amet praesentium deserunt ex commodi tempore fuga voluptatem. Sit, sapiente.",
  //   link: "/",
  // },
];

export const testimonials = [
  {
    name: "John Doe",
    job: "Full Stack Developer",
    image: "https://randomuser.me/api/portraits/men/1.jpg",
    review:
      "The next-saas-stripe-starter repo has truly revolutionized my development workflow. With its comprehensive features and seamless integration with Stripe, I've been able to build and deploy projects faster than ever before. The documentation is clear and concise, making it easy to navigate through the setup process. I highly recommend next-saas-stripe-starter to any developer.",
  },
  {
    name: "Alice Smith",
    job: "UI/UX Designer",
    image: "https://randomuser.me/api/portraits/women/2.jpg",
    review:
      "Thanks to next-saas-stripe-starter, I've been able to create modern and attractive user interfaces in record time. The starter kit provides a solid foundation for building sleek and intuitive designs, allowing me to focus more on the creative aspects of my work.",
  },
  {
    name: "David Johnson",
    job: "DevOps Engineer",
    image: "https://randomuser.me/api/portraits/men/3.jpg",
    review:
      "Thanks to next-saas-stripe-starter, I was able to streamline the entire process and get payments up and running in no time. ",
  },
  {
    name: "Michael Wilson",
    job: "Project Manager",
    image: "https://randomuser.me/api/portraits/men/5.jpg",
    review:
      "I'm impressed by the quality of code and clear documentation of next-saas-stripe-starter. Kudos to the team!",
  },
  {
    name: "Sophia Garcia",
    job: "Data Analyst",
    image: "https://randomuser.me/api/portraits/women/6.jpg",
    review:
      "next-saas-stripe-starter provided me with the tools I needed to efficiently manage user data. Thank you so much!",
  },
  {
    name: "Emily Brown",
    job: "Marketing Manager",
    image: "https://randomuser.me/api/portraits/women/4.jpg",
    review:
      "next-saas-stripe-starter has been an invaluable asset in my role as a marketing manager. With its seamless integration with Stripe, I've been able to launch targeted marketing campaigns with built-in payment functionality, allowing us to monetize our products and services more effectively.",
  },
];
